version: '3.8'
services:
  analyzer:
    build: .
    volumes:
      - ./data:/app/data
      - ./${DATA_PATHS__REPORTS_DIR}:/app/${DATA_PATHS__REPORTS_DIR}
      - ./${DATA_PATHS__DATABASE_FILE}:/app/${DATA_PATHS__DATABASE_FILE}
    env_file:
      - .env