services:
  app:
    build: .
    volumes:
      - ./data:/app/data
      - ./${DATA_PATHS__REPORTS_DIR}:/app/${DATA_PATHS__REPORTS_DIR}
      - ./db:/app/db
    environment:
      - DATABASE__PATH=/app/${DATABASE__PATH}
      - DATA_PATHS__REPORTS_DIR=/app/${DATA_PATHS__REPORTS_DIR}
    env_file:
      - .env
    command: python run_pipeline.py
